name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  express-broker:
    name: Express Broker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: douala/express-broker
          image_tag: latest
      - name: Rancher Deploy
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.CLUSTER_ID }}
          project_id: ${{ secrets.PROJECT_ID }}
          namespace: ${{ secrets.NAMESPACE }}
          deployment: ${{ secrets.DEPLOYMENT }}
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/douala/express-broker:latest
